/* ============================================================================
 * Smartness · Shorts Lab — app.js   (vanilla, no build, no libraries)
 * ----------------------------------------------------------------------------
 * DATA CONTRACT (the three JSON files this app consumes / writes). AI + HUMAN
 * PARITY: a human edit and an AI edit to these files are indistinguishable.
 *
 * 1) data.json  (GENERATED by build_dashboard.py — READ ONLY artifact)
 *    {
 *      "generated": "<iso|null>",
 *      "videos":      [ Video, ... ],        // posted shorts (kind:"posted")
 *      "predictions": [ Prediction, ... ],   // pre-post predictions (kind:"prediction")
 *      "schema":      { version, groups:[Group,...] }  // == experiment_variables.json
 *    }
 *
 *    Video {
 *      kind:"posted", id, slug, title, base, publish:"YYYY-MM-DD",
 *      bucket:"Short 20-35s"|"Long 45-65s"|"Mid 36-44s"|">65s",
 *      duration, swipe(stayed-to-watch %), avd(%), views, relret|null,
 *      topic, version_label, status:"posted", strip:"filmstrips/x.jpg",
 *      url:"https://youtube.com/shorts/<id>", script:"  0s: ...\n",
 *      features:{ "Visual (AI)":{...}, "Pixel":{...}, "Audio":{...}, "Hook/words":{...} }
 *    }
 *    Prediction {
 *      kind:"prediction", id, slug, title, base, source_video_id,
 *      version_label, status:"prediction", bucket, duration, note,
 *      pred_swipe:{point,range:[lo,hi],band,vs_original}, pred_avd:{...},
 *      strip, script,
 *      how_to_change_it:[{change,detail,fixes:"swipe"|"avd"|"keep"}],
 *      features:{ "Visual (AI ensemble)":{...}, ... "Scorecard":{value} },
 *      actual:{swipe|null, avd|null, views|null, verdict|null, error|null}
 *    }
 *
 * 2) experiments.json  (HUMAN + AI read/write — golden source for tests)
 *    { "updated":"<iso|null>", "experiments":[ Experiment, ... ] }
 *    Experiment { id:"exp_<ms>", _short:"<base/slug grouping key>", _ts:<ms>,
 *                 ...all schema field keys exactly... }
 *    Field keys EQUAL schema.groups[].fields[].key  (contract test).
 *
 * 3) findings.json  (AI read/write)
 *    { "updated":"YYYY-MM-DD", "note":"...",
 *      "findings":[ {id,icon,title,trust:"validated"|"directional"|"craft"|"method",
 *                    body,evidence,bucket,levers:[...]} ] }
 *
 * GitHub sync: experiments.json lives at GH.owner/GH.repo/GH.path. ghLoad GETs
 * it; ghSave PUTs with sha. On load: MERGE remote+local by id; NEVER wipe local
 * with an empty/unreachable remote. Token in localStorage only, never logged/URL.
 * ========================================================================== */

'use strict';

/* ----------------------------------------------------------------- config -- */
const GH = { owner:'lman80', repo:'smartness-shorts-lab', path:'experiments.json', branch:'main' };
const LS = {
  token:    'smartness_gh_token',
  exps:     'smartness_experiments_v1',
  names:    'smartness_name_overrides_v1',
  draft:    'smartness_addtest_draft_v1',
  ui:       'smartness_ui_v1',   // {sort,dir,filter,view} mirror
};
const TOTAL_FIELDS = 33; // fallback; recomputed from schema after load

/* ------------------------------------------------------------- app state -- */
const state = {
  videos:      [],
  predictions: [],
  schema:      null,
  experiments: [],   // human/AI tests (merged remote+local)
  groups:      [],   // memoized buildGroups() output; rebuilt on data mutation
  findings:    null,
  names:       loadJSON(LS.names, {}),     // {groupKey: displayName}
  generated:   null,
  // sha + connection
  sha:        null,
  token:      localStorage.getItem(LS.token) || '',
  online:     false,
  lastSync:   null,
  ghHandle:   null,
  // ui
  view:       'grid',     // grid | table
  tab:        'library',  // library | findings
  sort:       'date',
  dir:        'desc',
  filter:     'all',
  q:          '',
};

/* ----------------------------------------------------------------- helpers */
function $(s, r){ return (r||document).querySelector(s); }
function $$(s, r){ return Array.from((r||document).querySelectorAll(s)); }
function esc(s){
  return String(s==null?'':s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
}
function loadJSON(key, fb){
  try{ const v = JSON.parse(localStorage.getItem(key)); return v==null?fb:v; }catch(e){ return fb; }
}
function fmtViews(n){
  if(n==null || isNaN(n)) return '—';
  n = +n;
  if(n>=1e6) return (n/1e6).toFixed(n>=1e7?0:1).replace(/\.0$/,'')+'M';
  if(n>=1e3) return (n/1e3).toFixed(n>=1e4?0:1).replace(/\.0$/,'')+'K';
  return String(Math.round(n));
}
function pct(n, d){
  if(n==null || isNaN(n)) return '—';
  return (+n).toFixed(d==null?0:d)+'%';
}
function num(n, d){
  if(n==null || isNaN(n)) return '—';
  return (+n).toFixed(d==null?0:d);
}
const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
function parseDate(s){
  if(!s) return null;
  const d = new Date(s.length<=10 ? s+'T00:00:00' : s);
  return isNaN(d) ? null : d;
}
function fmtDateAbs(s){
  const d = parseDate(s);
  if(!d) return null;
  return `${MONTHS[d.getMonth()]} ${d.getDate()}, ${d.getFullYear()}`;
}
function fmtDateRel(s){
  const d = parseDate(s);
  if(!d) return null;
  let sec = (Date.now() - d.getTime())/1000;
  const future = sec < 0; sec = Math.abs(sec);
  const t = [['yr',31536000],['mo',2592000],['wk',604800],['d',86400],['hr',3600],['min',60]];
  for(const [u,s2] of t){
    const v = Math.floor(sec/s2);
    if(v>=1) return future ? `in ${v} ${u}` : `${v} ${u} ago`;
  }
  return 'just now';
}
function relTime(iso){
  if(!iso) return '';
  return fmtDateRel(iso) || '';
}
function slugify(s){
  return String(s||'').toLowerCase().normalize('NFKD').replace(/[^\w\s-]/g,'').trim().replace(/[\s_]+/g,'-').replace(/-+/g,'-') || ('x'+Date.now());
}
function debounce(fn, ms){ let t; return (...a)=>{ clearTimeout(t); t=setTimeout(()=>fn(...a), ms); }; }
function isShort(b){ return /short/i.test(b||''); }
function isLong(b){ return /long/i.test(b||''); }

/* ============================================================================
 * NORMALISE INTO "ITEMS" (one item per version) THEN GROUP BY DISPLAY NAME
 * ========================================================================== */

// grouping key — base if present else slug-stem; used to merge versions/preds/exps
function groupKey(rec){
  return (rec.base || rec.title || rec.slug || rec.id || '').trim() || (rec.id||'');
}
function displayName(key, fallback){
  return state.names[key] || fallback || key;
}

// build a uniform "item" from posted/prediction/experiment record
function toItem(rec, kind){
  if(kind==='experiment'){
    const e = rec;
    const swipe = e.stayed_to_watch_pct, avd = e.avd_pct, views = e.views;
    const status = /posted/i.test(e.status||'') ? 'posted'
                 : (/edited/i.test(e.status||'') ? 'edited' : 'idea');
    return {
      kind:'experiment', raw:e, id:e.id,
      gkey: e._short || groupKey({base:e.product, title:e.product, slug:e.id}),
      title: e.product || 'Untitled experiment',
      base: e.product || 'Untitled experiment',
      version_label: e.version_label || 'experiment',
      notes: e.notes || '',
      topic: '',
      publish: null,
      bucket: bucketFromLen(e.length_sec),
      swipe: numOrNull(swipe), avd: numOrNull(avd), views: numOrNull(views),
      relret: null,
      strip: e.strip || null,
      url: e.youtube_url || null,
      script: '',
      status,
      ts: (e._ts!=null ? +e._ts : (Number(String(e.id||'').replace(/\D/g,'')) || 0)),
    };
  }
  // posted | prediction (from data.json)
  // NEW SHAPE: a version may carry a nested `prediction` object
  //   prediction = {pred_swipe:{point,range,band,vs_original}, pred_avd:{...},
  //                 verdict, error, how_to_change_it:[...], scorecard, note}
  // A RESOLVED prediction is kind:'posted' (the uploaded re-edit) WITH a nested
  // .prediction and real metrics. A PENDING prediction is kind:'prediction'
  // with .prediction but null actual metrics (a planned future version).
  // LEGACY SHAPE: prediction fields sat top-level (rec.pred_swipe / rec.actual);
  // resolve either so older data.json still renders.
  const nested = rec.prediction || null;
  // a legacy prediction record (top-level pred_swipe) → synthesize the nested obj
  const predObj = nested || (rec.pred_swipe ? {
    pred_swipe: rec.pred_swipe, pred_avd: rec.pred_avd,
    verdict: rec.actual && rec.actual.verdict,
    error: rec.actual && rec.actual.error,
    how_to_change_it: rec.how_to_change_it,
    note: rec.note,
  } : null);
  const isPred = kind==='prediction';
  // honour the record's own kind/status when present (a resolved prediction in
  // the predictions[] array is really kind:'posted'); else fall back to the
  // array it came from.
  const realKind   = rec.kind || (isPred ? 'prediction' : 'posted');
  const realStatus = rec.status || (isPred ? 'prediction' : 'posted');
  // actual metrics: prefer top-level real numbers, else rec.actual. NEVER fall
  // back to the predicted point — it.swipe/it.avd must hold REAL posted metrics
  // only (null while pending), so range badges, sortKey('stayed'/'avd') and KPI
  // medians never mix fabricated predictions into actual-metric aggregates. The
  // predicted point is read exclusively from it.prediction.pred_swipe.point in
  // the prediction panel / card-pred rendering.
  const ac = rec.actual || {};
  const swipeVal = rec.swipe!=null ? rec.swipe : (ac.swipe!=null ? ac.swipe : null);
  const avdVal   = rec.avd!=null ? rec.avd : (ac.avd!=null ? ac.avd : null);
  const viewsVal = rec.views!=null ? rec.views : ac.views;
  return {
    kind: realKind, raw:rec, id:rec.id, slug:rec.slug,
    gkey: groupKey(rec),
    title: rec.title || rec.base || 'Untitled',
    base: rec.base || rec.title || 'Untitled',
    version_label: rec.version_label || (realKind==='prediction'?'prediction':'original'),
    notes: rec.note || '',
    topic: rec.topic || '',
    publish: rec.publish || null,
    bucket: rec.bucket || '',
    swipe: numOrNull(swipeVal),
    avd: numOrNull(avdVal),
    views: numOrNull(viewsVal),
    relret: numOrNull(rec.relret),
    strip: rec.strip || null,
    url: rec.url || (rec.id && realKind!=='prediction' ? `https://www.youtube.com/shorts/${rec.id}` : null),
    script: rec.script || '',
    status: realStatus,
    prediction: predObj,            // nested prediction (or null)
    actual: rec.actual || null,
    ts: parseDate(rec.publish)?.getTime() || 0,
  };
}
function numOrNull(v){ return (v==null || v===''||isNaN(v)) ? null : +v; }
function bucketFromLen(L){
  L = +L;
  if(!L || isNaN(L)) return '';
  if(L<=35) return 'Short 20-35s';
  if(L<=44) return 'Mid 36-44s';
  if(L<=65) return 'Long 45-65s';
  return '>65s';
}

// build all items + groups
function buildGroups(){
  const items = [];
  state.videos.forEach(v => items.push(toItem(v,'posted')));
  state.predictions.forEach(p => items.push(toItem(p,'prediction')));
  state.experiments.forEach(e => items.push(toItem(e,'experiment')));

  const map = new Map();
  for(const it of items){
    const k = it.gkey;
    if(!map.has(k)) map.set(k, { key:k, items:[] });
    map.get(k).items.push(it);
  }
  const groups = [];
  for(const g of map.values()){
    // versions newest first: status rank, then ts desc. Without the rank tie-in,
    // an experiment's large _ts could outrank real posts and all null-publish
    // items (ts:0) would pile up in arbitrary insertion order.
    const rank = {posted:0, resolved:1, prediction:2, edited:3, idea:4, experiment:5};
    g.items.sort((a,b)=>{
      const ra = rank[a.status]==null?9:rank[a.status];
      const rb = rank[b.status]==null?9:rank[b.status];
      if(ra!==rb) return ra-rb;
      return (b.ts||0)-(a.ts||0);
    });
    // pick representative = best posted version (highest views), else first
    const posted = g.items.filter(i=>i.kind==='posted');
    let rep;
    if(posted.length){
      rep = posted.slice().sort((a,b)=>(b.views||0)-(a.views||0))[0];
    } else {
      rep = g.items[0];
    }
    g.rep = rep;
    // NAME the short after its ORIGINAL (earliest-posted) version — stable, so a newer
    // re-edit with more views doesn't rename the short. Falls back to oldest item.
    const byDate = g.items.slice().sort((a,b)=>{
      const da=parseDate(a.publish), db=parseDate(b.publish);
      if(da&&db) return da-db; if(da) return -1; if(db) return 1; return (a.ts||0)-(b.ts||0);
    });
    const nameRep = (byDate.filter(i=>i.kind==='posted')[0]) || byDate[0] || rep;
    g.display = displayName(g.key, nameRep.title);
    g.versionCount = g.items.length;
    // swipe range across versions w/ swipe
    const sw = g.items.map(i=>i.swipe).filter(v=>v!=null);
    g.swMin = sw.length?Math.min(...sw):null;
    g.swMax = sw.length?Math.max(...sw):null;
    g.hasPosted = posted.length>0;
    // a "prediction" group has either a pending prediction version OR a posted
    // re-edit that carries a nested .prediction (resolved prediction).
    g.hasPrediction = g.items.some(i=>i.kind==='prediction' || i.prediction);
    g.hasExperiment = g.items.some(i=>i.kind==='experiment');
    // BEST = highest stayed-to-watch among POSTED versions (for the timeline badge)
    let best=null;
    for(const i of posted){ if(i.swipe!=null && (best==null || i.swipe>best.swipe)) best=i; }
    g.bestId = best ? best.id : null;
    groups.push(g);
  }
  return groups;
}

// Memoized access: rebuild only when the underlying data mutates (boot, save,
// delete, rename, merge). All read paths use getGroups() so a single render()
// no longer rebuilds groups 4+ times.
function rebuildGroups(){ state.groups = buildGroups(); return state.groups; }
function getGroups(){ return state.groups; }

/* ============================================================================
 * FILTERING / SORTING / RENDER PIPELINE
 * ========================================================================== */
function matchesQuery(g, q){
  if(!q) return true;
  q = q.toLowerCase();
  return g.items.some(i =>
    (i.title||'').toLowerCase().includes(q) ||
    (i.version_label||'').toLowerCase().includes(q) ||
    (i.notes||'').toLowerCase().includes(q) ||
    (i.topic||'').toLowerCase().includes(q) ||
    (g.display||'').toLowerCase().includes(q)
  );
}
function passesFilter(g, f){
  switch(f){
    case 'posted':     return g.hasPosted;
    case 'predicted':  return g.hasPrediction;
    case 'mine':       return g.hasExperiment;
    case 'short':      return g.items.some(i=>isShort(i.bucket));
    case 'long':       return g.items.some(i=>isLong(i.bucket));
    default:           return true;
  }
}
function sortKey(g){
  const r = g.rep;
  switch(state.sort){
    case 'views':    return r.views||0;
    case 'stayed':   return r.swipe||0;
    case 'avd':      return r.avd||0;
    case 'versions': return g.versionCount;
    case 'az':       return (g.display||'').toLowerCase();
    case 'date':
    default:         return r.ts||0;
  }
}
function computeView(){
  let groups = getGroups().slice();
  groups = groups.filter(g => passesFilter(g, state.filter) && matchesQuery(g, state.q));
  const mul = state.dir==='asc'?1:-1;
  groups.sort((a,b)=>{
    const ka=sortKey(a), kb=sortKey(b);
    // symmetric + string-coercing: if either side is a string (az), compare as
    // strings so a non-string counterpart can't crash localeCompare.
    if(typeof ka==='string' || typeof kb==='string') return String(ka).localeCompare(String(kb))*mul;
    return (ka-kb)*mul;
  });
  return groups;
}

// filter chip counts (independent of active filter — always vs query only)
function chipCounts(){
  let groups = getGroups().filter(g => matchesQuery(g, state.q));
  return {
    all:   groups.length,
    posted:groups.filter(g=>g.hasPosted).length,
    predicted:groups.filter(g=>g.hasPrediction).length,
    mine:  groups.filter(g=>g.hasExperiment).length,
    short: groups.filter(g=>g.items.some(i=>isShort(i.bucket))).length,
    long:  groups.filter(g=>g.items.some(i=>isLong(i.bucket))).length,
  };
}

const CHIP_DEFS = [
  ['all','All'],['posted','Posted'],['predicted','Predicted'],['mine','My experiments'],
  ['short','Short 20-35s'],['long','Long 45-65s'],
];
function renderChips(){
  const counts = chipCounts();
  $('#chips').innerHTML = CHIP_DEFS.map(([k,label])=>
    `<button type="button" role="radio" aria-checked="${state.filter===k}" class="chip ${state.filter===k?'is-active':''}" data-filter="${k}">
       ${esc(label)} <span class="ct">${counts[k]}</span>
     </button>`
  ).join('');
}

const SORT_LABELS = {date:'Date',views:'Views',stayed:'Stayed-to-watch',avd:'AVD',versions:'# versions',az:'A–Z'};
function renderKPI(groups){
  const posted = groups.filter(g=>g.hasPosted);
  const swipes = posted.map(g=>g.rep.swipe).filter(v=>v!=null).sort((a,b)=>a-b);
  const med = swipes.length ? swipes[Math.floor(swipes.length/2)] : null;
  const arrow = state.dir==='asc'?'↑':'↓';
  let parts = [`Showing <b>${groups.length}</b> shorts`];
  if(posted.length) parts.push(`<b>${posted.length}</b> posted`);
  if(med!=null) parts.push(`median stayed-to-watch <b>${pct(med)}</b>`);
  parts.push(`sorted by <b>${SORT_LABELS[state.sort]} ${arrow}</b>`);
  $('#kpi').innerHTML = parts.join(' <span class="sep">·</span> ');
}

/* ----------------------------------------------------------- render grid -- */
function stripHTML(item, cls){
  if(item.strip) return `<div class="${cls}"><img src="${esc(item.strip)}" alt="opening frames" loading="lazy"></div>`;
  return `<div class="${cls}"><div class="no-strip">no filmstrip yet</div></div>`;
}
function kindTag(g){
  if(g.rep.kind==='prediction') return `<span class="kind-tag kind-prediction">Prediction</span>`;
  if(g.rep.kind==='experiment') return `<span class="kind-tag kind-experiment">My test</span>`;
  return '';
}
// display-only swipe for a card/row: the REAL stayed-to-watch, or — for a
// pending prediction (no actual) — its predicted point. Never used in
// aggregates (range/sort/KPI); those read it.swipe (real only) exclusively.
function repSwipe(it){
  if(it.swipe!=null) return it.swipe;
  if(it.kind==='prediction' && it.prediction && it.prediction.pred_swipe){
    return numOrNull(it.prediction.pred_swipe.point);
  }
  return null;
}
function renderGrid(groups){
  const grid = $('#grid');
  if(!groups.length){ grid.innerHTML=''; return; }
  grid.innerHTML = groups.map(g=>{
    const r = g.rep;
    const rSwipe = repSwipe(r);          // real metric, or predicted point for a pending prediction
    const abs = fmtDateAbs(r.publish), rel = fmtDateRel(r.publish);
    const dateLine = abs ? `Posted ${esc(abs)} <span class="rel">· ${esc(rel)}</span>` :
                     (r.kind==='prediction' ? 'Predicted — not posted' : 'Not posted');
    const stayedGood = rSwipe!=null && rSwipe>=75 ? 'stayed-good' : '';
    const range = (g.swMin!=null && g.swMax!=null && g.versionCount>1 && g.swMin!==g.swMax)
      ? `<span class="badge range">${num(g.swMin)}–${num(g.swMax)}%</span>` : '';
    const ytBtn = r.url ? `<a class="btn btn-yt card-yt" href="${esc(r.url)}" target="_blank" rel="noopener" data-stop>▶ YouTube</a>` : '';
    return `
      <article class="card" data-key="${esc(g.key)}">
        <div class="card-strip">
          ${kindTag(g)}
          ${ytBtn}
          ${r.strip?`<img src="${esc(r.strip)}" alt="opening frames" loading="lazy">`:`<div class="no-strip">no filmstrip yet</div>`}
        </div>
        <div class="card-body">
          <h3 class="card-title">${esc(g.display)}</h3>
          <div class="card-date">${dateLine}</div>
          <div class="card-metrics">
            <div class="metric-big ${stayedGood}">
              <span class="v">${rSwipe!=null?num(rSwipe):'—'}<span class="pct">${rSwipe!=null?'%':''}</span></span>
              <span class="l">${r.kind==='prediction'?'pred. stayed':'stayed'}</span>
            </div>
            <div class="metric-sm"><span class="v">${fmtViews(r.views)}</span><span class="l">views</span></div>
            <div class="metric-sm"><span class="v">${r.avd!=null?num(r.avd)+'%':'—'}</span><span class="l">avd</span></div>
          </div>
          <div class="card-foot">
            <span class="badge">${g.versionCount} version${g.versionCount>1?'s':''}</span>
            ${range}
            ${r.bucket?`<span class="badge bucket">${esc(shortBucket(r.bucket))}</span>`:''}
            <div class="card-actions" data-stop>
              <button type="button" class="btn btn-sm btn-primary" data-add="${esc(g.key)}">+ Add Test</button>
              <div class="menu-wrap">
                <button type="button" class="menu-btn" data-menu aria-label="More">⋯</button>
                <div class="menu">
                  <button type="button" data-rename="${esc(g.key)}">Rename short</button>
                  ${g.hasExperiment?`<button type="button" data-edit="${esc(g.key)}">Edit experiment</button>
                  <button type="button" class="danger" data-del="${esc(g.key)}">Delete experiment</button>`:''}
                </div>
              </div>
            </div>
          </div>
        </div>
      </article>`;
  }).join('');
}
function shortBucket(b){
  if(isShort(b)) return 'Short';
  if(isLong(b)) return 'Long';
  if(/mid/i.test(b)) return 'Mid';
  if(/>65/.test(b)) return '65s+';
  return b;
}

/* ---------------------------------------------------------- render table -- */
function renderTable(groups){
  const wrap = $('#table-wrap');
  if(!groups.length){ wrap.innerHTML=''; return; }
  const rows = groups.map(g=>{
    const r=g.rep;
    const rSwipe = repSwipe(r);          // real metric, or predicted point for a pending prediction
    const abs=fmtDateAbs(r.publish);
    const good = rSwipe!=null && rSwipe>=75 ? 't-good':'';
    const ytBtn = r.url?`<a class="btn btn-yt btn-sm" href="${esc(r.url)}" target="_blank" rel="noopener" data-stop>▶</a>`:'';
    return `<tr data-key="${esc(g.key)}">
      <td class="t-thumb">${r.strip?`<img src="${esc(r.strip)}" alt="" loading="lazy">`:''}</td>
      <td class="t-title">${esc(g.display)}<small>${esc(r.version_label)}${g.versionCount>1?` · ${g.versionCount} versions`:''}</small></td>
      <td>${abs?esc(abs):(r.kind==='prediction'?'predicted':'—')}</td>
      <td class="num ${good}">${rSwipe!=null?num(rSwipe)+(r.kind==='prediction'?'%*':'%'):'—'}</td>
      <td class="num">${r.avd!=null?num(r.avd)+'%':'—'}</td>
      <td class="num">${fmtViews(r.views)}</td>
      <td class="num">${g.versionCount}</td>
      <td class="t-act" data-stop>${ytBtn}
        <button type="button" class="btn btn-sm" data-add="${esc(g.key)}">+ Test</button></td>
    </tr>`;
  }).join('');
  wrap.innerHTML = `<table class="tbl">
    <thead><tr>
      <th></th><th>Title</th><th>Date posted</th>
      <th class="num">Stayed %</th><th class="num">AVD %</th><th class="num">Views</th><th class="num"># ver</th><th></th>
    </tr></thead><tbody>${rows}</tbody></table>`;
}

/* --------------------------------------------------------------- render ---- */
function render(){
  rebuildGroups();          // single rebuild per render; readers use the memo
  renderChips();
  const groups = computeView();
  renderKPI(groups);
  $('#empty').hidden = groups.length>0;
  if(state.view==='grid'){
    $('#grid').hidden = false; $('#table-wrap').hidden = true;
    renderGrid(groups);
  } else {
    $('#grid').hidden = true; $('#table-wrap').hidden = false;
    renderTable(groups);
  }
  syncToolbarUI();
  syncURL();
  persistUI();
}
function persistUI(){
  try{ localStorage.setItem(LS.ui, JSON.stringify({sort:state.sort, dir:state.dir, filter:state.filter, view:state.view})); }catch(e){}
}

function syncToolbarUI(){
  $('#sort').value = state.sort;
  $('#dir').textContent = state.dir==='asc'?'▲':'▼';
  $$('.vt-btn').forEach(b=>{
    const on = b.dataset.view===state.view;
    b.classList.toggle('is-active', on); b.setAttribute('aria-pressed', on);
  });
  $('#search').value = state.q;
}

/* ============================================================================
 * URL STATE  (?short=&sort=&dir=&filter=&q=)  — token NEVER in URL
 * ========================================================================== */
const syncURL = debounce(()=>{
  const p = new URLSearchParams();
  if(state.sort!=='date') p.set('sort', state.sort);
  if(state.dir!=='desc')  p.set('dir', state.dir);
  if(state.filter!=='all')p.set('filter', state.filter);
  if(state.q)             p.set('q', state.q);
  if(state.view!=='grid') p.set('view', state.view);
  if(state.tab!=='library')p.set('tab', state.tab);
  const openKey = $('#detail').open ? $('#detail').dataset.key : '';
  if(openKey){ const g = getGroups().find(x=>x.key===openKey); if(g) p.set('short', g.rep.slug || slugify(g.key)); }
  const qs = p.toString();
  history.replaceState(null,'', qs?('?'+qs):location.pathname);
}, 200);

function readURL(){
  const p = new URLSearchParams(location.search);
  if(p.get('sort')) state.sort = p.get('sort');
  if(p.get('dir'))  state.dir  = p.get('dir');
  if(p.get('filter'))state.filter = p.get('filter');
  if(p.get('q'))    state.q    = p.get('q');
  if(p.get('view')) state.view = p.get('view');
  if(p.get('tab'))  state.tab  = p.get('tab');
  return p.get('short');
}

/* ============================================================================
 * DETAIL DRAWER
 * ========================================================================== */
function findGroup(key){ return getGroups().find(g=>g.key===key); }
function findGroupBySlug(slug){
  return getGroups().find(g => (g.rep.slug||slugify(g.key))===slug);
}

function openDetail(key){
  const g = findGroup(key);
  if(!g) return;
  const r = g.rep;
  const dlg = $('#detail');
  dlg.dataset.key = key;
  $('#detail-inner').innerHTML = detailHTML(g);
  if(!dlg.open) dlg.showModal();
  wireDetail(dlg, g);
  syncURL();
}

// retention drop-off sparkline — rendered ONLY when the record carries
// drop-off data (a `retention` array, or init/lost1/lost3 fields). data.json
// does not emit this yet, so this is inert today and safe to ship.
function sparkHTML(raw){
  if(!raw) return '';
  let vals = null;
  if(Array.isArray(raw.retention) && raw.retention.length){
    vals = raw.retention.map(Number).filter(v=>!isNaN(v));
  } else if(raw.init!=null || raw.lost1!=null || raw.lost3!=null){
    const init = +raw.init || 100;
    vals = [init, init-(+raw.lost1||0), init-(+raw.lost1||0)-(+raw.lost3||0)];
  }
  if(!vals || !vals.length) return '';
  const max = Math.max(...vals, 1);
  const bars = vals.map(v=>`<span class="bar" style="height:${Math.max(3,Math.round((v/max)*34))}px"></span>`).join('');
  return `<div class="spark">${bars}</div>
    <div class="spark-cap"><span>retention drop-off</span><span>${num(vals[0])}% → ${num(vals[vals.length-1])}%</span></div>`;
}

/* ----------------------------------------------------------------------------
 * DETAIL DRAWER = SHORT-CENTRIC VERSIONS TIMELINE
 * The drawer shows ONE short (a group) and all of its versions as a vertical
 * timeline, newest at top. Header = display name + version summary + add-test.
 * Each node = a version card (filmstrip, status pill, metrics, YouTube, an
 * optional 🔮 prediction-vs-actual panel, expandable script + AI features).
 * -------------------------------------------------------------------------- */

// status → pill class + human label (Posted / Predicted / Resolved / Experiment / …)
function statusMeta(it){
  if(it.kind==='prediction') return {cls:'tl-pill-pred',  label:'Predicted'};
  if(it.kind==='experiment'){
    if(it.status==='posted') return {cls:'tl-pill-posted', label:'Posted'};
    return {cls:'tl-pill-exp', label:'Experiment'};
  }
  // a resolved prediction = a posted re-edit that carried a nested prediction
  // and now has real metrics → distinct blue "Resolved" pill.
  if(it.prediction && it.swipe!=null) return {cls:'tl-pill-resolved', label:'Resolved'};
  return {cls:'tl-pill-posted', label:'Posted'};
}

function detailHTML(g){
  // versions, newest first (g.items already sorted by ts desc in buildGroups)
  const items = g.items.slice();
  // earliest / latest posted-or-any date for the subtitle
  const dated = items.filter(i=>i.publish).map(i=>i.publish).sort();
  const earliest = dated.length ? fmtDateAbs(dated[0]) : null;
  const latest   = dated.length ? fmtDateAbs(dated[dated.length-1]) : null;
  const rep = g.rep;
  const bucket = rep.bucket
    ? `<span class="tl-bucket">${esc(shortBucket(rep.bucket))} · ${esc(rep.bucket)}</span>` : '';

  let subParts = [`${g.versionCount} version${g.versionCount>1?'s':''}`];
  if(earliest) subParts.push(`first posted ${esc(earliest)}`);
  if(latest && latest!==earliest) subParts.push(`latest ${esc(latest)}`);
  const sub = subParts.join(' · ');

  const nodes = items.map((it,i)=>timelineNodeHTML(it, g, i===0)).join('');

  return `
    <div class="drawer-head tl-head">
      <div class="tl-head-main">
        <h2 class="drawer-title">${esc(g.display)}</h2>
        <p class="drawer-sub">${sub}</p>
        <div class="dh-buttons">
          <button type="button" class="btn btn-primary" data-add-detail="${esc(g.key)}">+ Add Test (new version)</button>
          ${bucket}
        </div>
      </div>
      <button type="button" class="x" data-close-detail aria-label="Close">✕</button>
    </div>
    <div class="detail-body tl-body">
      <ol class="timeline">${nodes}</ol>
    </div>`;
}

// one timeline node = connector (dot + line) + a version card
function timelineNodeHTML(it, g, isNewest){
  const meta = statusMeta(it);
  const abs = fmtDateAbs(it.publish);
  const rel = fmtDateRel(it.publish);
  // BEST star: only meaningful when comparing 2+ REAL posted versions. Gate the
  // count on the same posted set that g.bestId was computed from so a pending
  // prediction can never inflate the count and flip the star on a lone post.
  const isBest = g.bestId && it.id===g.bestId &&
                 g.items.filter(i=>i.kind==='posted').length>1;
  const stayedGood = it.swipe!=null && it.swipe>=75;

  // node dot colour mirrors the status pill
  const dotCls = meta.cls.replace('tl-pill-','tl-dot-');

  // date block — prominent on the node
  const dateBlock = abs
    ? `<div class="tl-date"><span class="tl-date-abs">${esc(abs)}</span>${rel?`<span class="tl-date-rel">${esc(rel)}</span>`:''}</div>`
    : (it.kind==='prediction'
        ? `<div class="tl-date tl-date-future"><span class="tl-date-abs">Awaiting upload</span><span class="tl-date-rel">planned version</span></div>`
        : `<div class="tl-date"><span class="tl-date-abs">Not posted</span></div>`);

  const strip = it.strip
    ? `<div class="tl-strip"><img src="${esc(it.strip)}" alt="opening frames" loading="lazy"></div>`
    : `<div class="tl-strip tl-strip-empty">no filmstrip yet</div>`;

  const ytBtn = it.url
    ? `<a class="btn btn-yt tl-yt" href="${esc(it.url)}" target="_blank" rel="noopener">▶ Open in YouTube</a>` : '';

  const predPanel = it.prediction ? predictionPanelHTML(it) : '';

  // expandable script
  const scriptBlock = it.script ? `
    <details class="tl-expand">
      <summary>Second-by-second script</summary>
      <div class="tl-expand-body"><pre class="script-pre">${esc(it.script)}</pre></div>
    </details>` : '';

  // expandable AI features
  const featBlock = (it.raw && it.raw.features) ? `
    <details class="tl-expand">
      <summary>AI feature scores</summary>
      <div class="tl-expand-body">${featuresHTML(it.raw.features)}</div>
    </details>` : '';

  return `
    <li class="tl-node ${isNewest?'is-newest':''}">
      <div class="tl-rail"><span class="tl-dot ${dotCls}"></span></div>
      <div class="tl-card">
        <div class="tl-card-top">
          ${dateBlock}
          <div class="tl-pills">
            <span class="tl-pill ${meta.cls}">${esc(meta.label)}</span>
            ${isBest?`<span class="tl-pill tl-pill-best">★ BEST</span>`:''}
          </div>
        </div>
        <div class="tl-version-label">${esc(it.version_label)}</div>
        ${strip}
        <div class="tl-metrics">
          <div class="tl-metric ${stayedGood?'is-good':''}">
            <span class="tl-mv">${it.swipe!=null?num(it.swipe)+'%':'—'}</span>
            <span class="tl-ml">${it.kind==='prediction'?'Pred. stayed':'Stayed-to-watch'}</span>
          </div>
          <div class="tl-metric">
            <span class="tl-mv">${it.avd!=null?num(it.avd)+'%':'—'}</span>
            <span class="tl-ml">AVD</span>
          </div>
          <div class="tl-metric">
            <span class="tl-mv">${fmtViews(it.views)}</span>
            <span class="tl-ml">Views</span>
          </div>
        </div>
        ${it.notes?`<div class="tl-note">${esc(it.notes)}</div>`:''}
        ${predPanel}
        <div class="tl-card-actions">
          ${ytBtn}
          <button type="button" class="btn btn-sm" data-clone="${esc(it.id)}">+ Add Test (clone this)</button>
        </div>
        ${scriptBlock}
        ${featBlock}
      </div>
    </li>`;
}

// 🔮 prediction-vs-actual panel — rendered INSIDE a version card that carries
// a nested .prediction (resolved OR pending).
function predictionPanelHTML(it){
  const p = it.prediction || {};
  const ps = p.pred_swipe || {}, pa = p.pred_avd || {};
  const predPt = ps.point;
  const actual = it.swipe;                          // real stayed-to-watch (null if pending)
  const pending = (it.kind==='prediction') || actual==null;

  // verdict: prefer the model's own verdict, else derive from error
  let verdict = p.verdict;
  if(!verdict && actual!=null && predPt!=null){
    const err = Math.abs(actual - predPt);
    verdict = err<=3?'HIT':(err<=7?'PARTIAL':'MISS');
  }
  const vClass = verdict==='HIT'?'tl-v-hit'
               : verdict==='PARTIAL'||verdict==='CLOSE'?'tl-v-partial'
               : verdict==='MISS'?'tl-v-miss':'tl-v-pending';
  const rangeTxt = ps.range ? ` (${ps.range[0]}–${ps.range[1]})` : '';

  // headline
  let headline;
  if(pending){
    headline = `<span class="tl-pred-pt">Predicted ${predPt!=null?num(predPt)+'%':'—'}${esc(rangeTxt)}</span>
                <span class="tl-pred-await">— awaiting upload</span>`;
  } else {
    const delta = (actual!=null && predPt!=null) ? (actual - predPt) : null;
    const deltaTxt = delta!=null ? `<span class="tl-pred-delta ${delta>=0?'pos':'neg'}">${delta>=0?'+':''}${num(delta)} pts</span>` : '';
    headline = `<span class="tl-pred-pt">Predicted ${predPt!=null?num(predPt)+'%':'—'}</span>
                <span class="tl-pred-arrow">→</span>
                <span class="tl-pred-actual">actual ${num(actual)}%</span>
                ${deltaTxt}`;
  }

  // expandable internals: how_to_change_it + scorecard + tested features
  const howto = (p.how_to_change_it||[]).map(h=>`
    <li class="${h.fixes==='keep'?'fix-keep':''}">
      <div class="ht-change">${esc(h.change)}</div>
      <div class="ht-detail">${esc(h.detail)}</div>
      <div class="ht-fixes">fixes: ${esc(h.fixes||'—')}</div>
    </li>`).join('');

  const detailBits = [];
  if(p.note) detailBits.push(`<div class="tl-pred-note">${esc(p.note)}</div>`);
  detailBits.push(`
    <div class="tl-pred-grid">
      <div class="tl-pred-cell"><span class="l">Predicted stayed</span><span class="v">${predPt!=null?num(predPt)+'%':'—'}${esc(rangeTxt)}</span>${ps.band||ps.vs_original?`<span class="b">${esc(ps.band||'')} ${esc(ps.vs_original||'')}</span>`:''}</div>
      <div class="tl-pred-cell"><span class="l">Predicted AVD</span><span class="v">${pa.point!=null?num(pa.point)+'%':'—'}${pa.range?` (${pa.range[0]}–${pa.range[1]})`:''}</span>${pa.band?`<span class="b">${esc(pa.band)}</span>`:''}</div>
      ${!pending?`<div class="tl-pred-cell"><span class="l">Actual stayed</span><span class="v">${actual!=null?num(actual)+'%':'—'}</span></div>
      <div class="tl-pred-cell"><span class="l">Actual AVD</span><span class="v">${it.avd!=null?num(it.avd)+'%':'—'}</span></div>`:''}
    </div>`);
  if(pa.rationale) detailBits.push(`<div class="tl-pred-rationale"><b>AVD rationale:</b> ${esc(pa.rationale)}</div>`);
  if(p.error) detailBits.push(`<div class="tl-pred-error">${esc(p.error)}</div>`);
  if(p.scorecard!=null){
    const sc = (typeof p.scorecard==='number') ? (Number.isInteger(p.scorecard)?p.scorecard:(+p.scorecard).toFixed(2)) : esc(p.scorecard);
    detailBits.push(`<div class="tl-pred-score"><span class="l">Scorecard</span><span class="v">${sc}</span></div>`);
  }
  if(howto) detailBits.push(`<div class="sec-label" style="margin-top:4px">How to change it</div><ul class="howto">${howto}</ul>`);
  // tested features (the prediction record's own feature scores)
  if(it.raw && it.raw.features) detailBits.push(`<div class="sec-label" style="margin-top:4px">Tested features</div>${featuresHTML(it.raw.features)}`);

  return `
    <div class="tl-pred ${vClass}">
      <div class="tl-pred-head">
        <span class="tl-pred-title">🔮 Prediction vs actual</span>
        ${verdict?`<span class="tl-verdict ${vClass}">${esc(verdict)}</span>`:`<span class="tl-verdict tl-v-pending">PENDING</span>`}
      </div>
      <div class="tl-pred-line">${headline}</div>
      ${ps.vs_original && pending?`<div class="tl-pred-vs">${esc(ps.vs_original)}</div>`:''}
      <details class="tl-pred-more">
        <summary>How it was changed · scorecard · tested features</summary>
        <div class="tl-pred-more-body">${detailBits.join('')}</div>
      </details>
    </div>`;
}

// AI vs measured grouping + trust where relevant
const TRUST_FEATURE = {face:'ai', object_clarity:'ai', opening_line_type:'ai', face_in_first_frame:'ai'};
function featuresHTML(features){
  return Object.keys(features).map(grp=>{
    const measured = /pixel/i.test(grp);
    const tag = measured ? `<span class="feat-tag tag-measured">measured</span>` : `<span class="feat-tag tag-ai">AI-interpreted</span>`;
    const obj = features[grp]||{};
    const keys = Object.keys(obj).filter(k=>k!=='_source');
    // single bare {value:n} group (e.g. prediction "Scorecard") — render the
    // group label as the row label instead of an unlabeled "value" row.
    if(keys.length===1 && keys[0]==='value'){
      const v = obj.value;
      const vv = (typeof v==='number') ? (Number.isInteger(v)?v:(+v).toFixed(2)) : esc(v);
      const src = obj._source?`<div class="f-evidence">${esc(obj._source)}</div>`:'';
      return `<div class="feat-group"><h4>${esc(grp)} ${tag}</h4>`+
             `<div class="feat-rows"><div class="feat-row"><span class="fk">${esc(grp)}</span>`+
             `<span class="fv">${vv===''?'—':vv}</span></div></div>${src}</div>`;
    }
    const rows = keys.map(k=>{
      const v = obj[k];
      const vv = (typeof v==='number') ? (Number.isInteger(v)?v:(+v).toFixed(2)) : esc(v);
      return `<div class="feat-row"><span class="fk">${esc(k)}</span><span class="fv">${vv===''?'—':vv}</span></div>`;
    }).join('');
    const src = obj._source?`<div class="f-evidence">${esc(obj._source)}</div>`:'';
    return `<div class="feat-group"><h4>${esc(grp)} ${tag}</h4><div class="feat-rows">${rows}</div>${src}</div>`;
  }).join('');
}

function wireDetail(dlg, g){
  $('[data-close-detail]', dlg)?.addEventListener('click', ()=>closeDetail());
  $('[data-add-detail]', dlg)?.addEventListener('click', ()=>openAddTest(g.key));
  $$('[data-clone]', dlg).forEach(b=>b.addEventListener('click', ()=>openAddTest(g.key, b.dataset.clone)));
}
function closeDetail(){
  const dlg = $('#detail');
  if(dlg.open) dlg.close();
  dlg.dataset.key='';
  syncURL();
}

/* ============================================================================
 * ADD & TEST DRAWER  (form from schema; prefill/clone; autosave draft)
 * ========================================================================== */
let atContext = { key:null, editId:null }; // editId set when editing existing exp

function schemaFields(){
  const out=[];
  (state.schema?.groups||[]).forEach(g=>g.fields.forEach(f=>out.push(f)));
  return out;
}
function totalFields(){ return schemaFields().length || TOTAL_FIELDS; }

// derive prefill values from a source item (clone-as-template)
function prefillFrom(item){
  if(!item) return {};
  const raw = item.raw||{};
  const feats = raw.features || {};
  const hk = feats['Hook/words'] || {};
  // posted videos use 'Visual (AI)' (sub-key `face`); predictions use
  // 'Visual (AI ensemble)' (sub-key `face_in_first_frame`). Resolve either.
  const vis = feats['Visual (AI)'] || feats['Visual (AI ensemble)'] || {};
  const faceVal = (vis.face!=null ? vis.face : vis.face_in_first_frame);
  const out = {
    product: item.base,
    topic: item.topic,
    length_sec: raw.duration!=null?Math.round(raw.duration):'',
    format: '',
    youtube_url: item.url||'',
    face_in_frame: (faceVal!=null && +faceVal>0) || faceVal===true || false,
    opening_line_type: mapLineType(hk.opening_line_type || hk.hook_archetype),
  };
  return out;
}
function mapLineType(t){
  if(!t) return '';
  if(/question/i.test(t)) return 'question (avoid)';
  if(/null|nothing/i.test(t)) return "null-state / 'nothing happens' (avoid)";
  return 'statement (good)';
}
const INHERIT_KEYS = ['product','topic','length_sec','face_in_frame','opening_line_type','youtube_url','format'];
// fields shown first as "lead levers" — the two graduated FIRST-FRAME levers
// per the brief are face + object clarity. The real schema has no single
// "object_clarity" field; clarity is expressed by product_size + sharpness +
// centered + contrast. These float to the top of the First Frame group and get
// the lever flag/styling. opening_line_type is the hook/words lead lever.
const LEVER_KEYS = ['face_in_frame','product_size','sharpness','centered','contrast','opening_line_type'];
const OPEN_GROUPS = {identify:true, identify_:true, first_frame:true, hook:true, outcomes:true, video_level:false};

function openAddTest(key, cloneId){
  atContext = { key:key||null, editId:null };
  // determine prefill source
  let prefill = {}, inherited = new Set();
  if(key){
    const g = findGroup(key);
    if(g){
      let src = cloneId ? g.items.find(i=>i.id===cloneId) : g.rep;
      prefill = prefillFrom(src||g.rep);
      INHERIT_KEYS.forEach(k=>{ if(prefill[k]!==''&&prefill[k]!=null&&prefill[k]!==false) inherited.add(k); });
    }
  }
  // restore an in-progress draft only for blank-new (no key, no editId)
  let values = Object.assign({}, prefill);
  if(!key){
    const draft = loadJSON(LS.draft, {});
    values = Object.assign(values, draft);
  }
  buildForm(values, inherited);
  $('#at-title').textContent = key ? `Add test → ${displayName(key, prefill.product||key)}` : 'New short (blank)';
  $('#at-sub').textContent = key ? 'Cloned from this short — change only what differs.' : 'Start a fresh experiment.';
  const dlg = $('#addtest');
  if(!dlg.open) dlg.showModal();
  updateCounter();
}

function openEditExperiment(key){
  const g = findGroup(key);
  const exp = g && g.items.find(i=>i.kind==='experiment');
  if(!exp) return;
  atContext = { key, editId: exp.id };
  buildForm(exp.raw, new Set());
  $('#at-title').textContent = `Edit experiment → ${esc(exp.title)}`;
  $('#at-sub').textContent = 'Editing an existing experiment version.';
  const dlg = $('#addtest');
  if(!dlg.open) dlg.showModal();
  updateCounter();
}

function buildForm(values, inherited){
  const form = $('#at-form');
  form.innerHTML = (state.schema?.groups||[]).map(grp=>{
    const open = OPEN_GROUPS[grp.key] !== undefined ? OPEN_GROUPS[grp.key] : true;
    // order: lead levers first within first_frame / hook
    let fields = grp.fields.slice();
    if(grp.key==='first_frame'||grp.key==='hook'){
      fields.sort((a,b)=>{
        const ai = LEVER_KEYS.indexOf(a.key), bi = LEVER_KEYS.indexOf(b.key);
        return (ai<0?99:ai)-(bi<0?99:bi);
      });
    }
    const body = fields.map(f=>fieldHTML(f, values[f.key], inherited.has(f.key))).join('');
    return `
      <details class="fgroup" data-grp="${esc(grp.key)}" ${open?'open':''}>
        <summary>${grp.icon?esc(grp.icon)+' ':''}${esc(grp.label)} <span class="grp-count" data-grpcount="${esc(grp.key)}"></span></summary>
        ${grp.help?`<div class="grp-help">${esc(grp.help)}</div>`:''}
        <div class="fgroup-body">${body}</div>
      </details>`;
  }).join('');
  wireForm();
}

function fieldHTML(f, val, inherited){
  const isLever = LEVER_KEYS.includes(f.key);
  const labelExtra = `${isLever?'<span class="lever-flag">lever</span>':''}${inherited?'<span class="inherited-flag">inherited</span>':''}`;
  const help = f.help?`<span class="fhelp">${esc(f.help)}</span>`:'';
  const lev = isLever?'lever':'';
  let control='';
  const v = val==null?'':val;
  switch(f.type){
    case 'textarea':
      control=`<textarea data-k="${f.key}" placeholder="${esc(f.placeholder||'')}">${esc(v)}</textarea>`; break;
    case 'number':
      control=`<input type="number" data-k="${f.key}" placeholder="${esc(f.placeholder||'')}" value="${esc(v)}">`; break;
    case 'select':
      control=`<select data-k="${f.key}"><option value="">—</option>${(f.options||[]).map(o=>`<option value="${esc(o)}" ${o===v?'selected':''}>${esc(o)}</option>`).join('')}</select>`; break;
    case 'toggle':
      control=`<label class="toggle"><input type="checkbox" data-k="${f.key}" ${v===true||v==='true'?'checked':''}><span class="track"></span><span class="tlabel">${v===true||v==='true'?'Yes':'No'}</span></label>`; break;
    case 'scale':{
      const min=f.min||1, max=f.max||5; let seg='';
      for(let i=min;i<=max;i++) seg+=`<button type="button" data-scale="${i}" class="${(+v)===i?'on':''}">${i}</button>`;
      control=`<div class="scale" data-k="${f.key}"><div class="seg">${seg}</div><div class="ends"><span>${esc(f.lo||'')}</span><span>${esc(f.hi||'')}</span></div></div>`;
      break;
    }
    case 'multiselect':{
      const cur = Array.isArray(v)?v:(v?String(v).split(',').map(s=>s.trim()):[]);
      control=`<div class="multi" data-k="${f.key}">${(f.options||[]).map(o=>`<button type="button" data-opt="${esc(o)}" class="${cur.includes(o)?'on':''}">${esc(o)}</button>`).join('')}</div>`;
      break;
    }
    default:
      control=`<input type="text" data-k="${f.key}" placeholder="${esc(f.placeholder||'')}" value="${esc(v)}">`;
  }
  return `<div class="field ${lev}" data-field="${f.key}" data-type="${f.type}">
    <label class="fl">${esc(f.label)} ${labelExtra}</label>
    ${control}${help}
  </div>`;
}

function wireForm(){
  const form = $('#at-form');
  // NOTE: form-level input/change delegation is attached ONCE in wireEvents()
  // (not here) so it does not accumulate each time the drawer is rebuilt.
  // The toggle/scale/multi listeners below are on freshly-rebuilt child nodes.
  // onFormChange explicitly SKIPS .toggle/.scale/.multi so a single interaction
  // does not double-fire markSet+updateCounter+saveDraft.
  // toggles
  $$('.toggle input', form).forEach(cb=>cb.addEventListener('change', e=>{
    e.target.closest('.toggle').querySelector('.tlabel').textContent = e.target.checked?'Yes':'No';
    markSet(e.target.closest('.field')); updateCounter(); saveDraft();
  }));
  // scales
  $$('.scale', form).forEach(sc=>sc.addEventListener('click', e=>{
    const b = e.target.closest('[data-scale]'); if(!b) return;
    const on = b.classList.contains('on');
    sc.querySelectorAll('button').forEach(x=>x.classList.remove('on'));
    if(!on) b.classList.add('on');
    markSet(sc.closest('.field')); updateCounter(); saveDraft();
  }));
  // multiselect
  $$('.multi', form).forEach(m=>m.addEventListener('click', e=>{
    const b = e.target.closest('[data-opt]'); if(!b) return;
    b.classList.toggle('on');
    markSet(m.closest('.field')); updateCounter(); saveDraft();
  }));
}
function onFormChange(e){
  const el = e.target;
  if(!el.matches('[data-k]')) return;
  // toggle/scale/multi have their own dedicated listeners (attached per-rebuild
  // in wireForm). Skip them here so a single interaction doesn't run
  // markSet+updateCounter+saveDraft twice (redundant writes + counter flicker).
  if(el.closest('.toggle, .scale, .multi')) return;
  markSet(el.closest('.field')); updateCounter(); saveDraft();
}
function markSet(field){
  if(!field) return;
  field.classList.toggle('is-set', !!fieldValue(field));
}

function fieldValue(field){
  const type = field.dataset.type;
  if(type==='toggle'){ const cb=$('input',field); return cb&&cb.checked?true:''; }
  if(type==='scale'){ const on=$('.scale .seg button.on',field); return on?+on.dataset.scale:''; }
  if(type==='multiselect'){ const ons=$$('.multi button.on',field).map(b=>b.dataset.opt); return ons.length?ons:''; }
  const el=$('[data-k]',field); if(!el) return '';
  const v=(el.value||'').trim();
  if(type==='number') return v===''?'':(+v);
  return v;
}
function collectForm(){
  const out={};
  $$('.field', $('#at-form')).forEach(f=>{
    const key=f.dataset.field;
    const v=fieldValue(f);
    if(v!=='' && !(Array.isArray(v)&&!v.length)) out[key]=v;
  });
  return out;
}
function updateCounter(){
  const total=totalFields();
  const setN=$$('.field', $('#at-form')).filter(f=>{ const v=fieldValue(f); return v!=='' && !(Array.isArray(v)&&!v.length); }).length;
  $('#at-counter').textContent=`${setN} / ${total} set`;
  // per-group counts
  $$('.fgroup', $('#at-form')).forEach(g=>{
    const gset = $$('.field', g).filter(f=>{ const v=fieldValue(f); return v!=='' && !(Array.isArray(v)&&!v.length); }).length;
    const all = $$('.field', g).length;
    g.querySelector('[data-grpcount]').textContent=`${gset}/${all}`;
  });
}
const saveDraft = debounce(()=>{
  if(atContext.key || atContext.editId) return; // only persist blank-new drafts
  try{ localStorage.setItem(LS.draft, JSON.stringify(collectForm())); }catch(e){}
}, 400);

async function saveVersion(){
  const data = collectForm();
  if(!data.product){ flashSave('Add a short / product name first', 'err'); $('details.fgroup')?.setAttribute('open',''); return; }
  const key = atContext.key || groupKey({base:data.product, title:data.product});
  let exp;
  if(atContext.editId){
    exp = state.experiments.find(e=>e.id===atContext.editId);
    if(!exp){
      // the experiment was deleted/merged away between open and save —
      // recreate it under the same id so the edit is not silently lost
      exp = { id:atContext.editId };
      state.experiments.push(exp);
    }
  } else {
    exp = { id:'exp_'+Date.now() };
    state.experiments.push(exp);
  }
  // wipe old schema keys then assign
  schemaFields().forEach(f=>{ delete exp[f.key]; });
  Object.assign(exp, data);
  exp._short = key;
  exp._ts = Date.now();
  exp.id = exp.id || ('exp_'+Date.now());

  persistLocal();
  localStorage.removeItem(LS.draft);
  $('#addtest').close();
  render();

  // sync to GitHub — surface success/failure feedback
  if(state.token){
    const ok = await ghSave();
    flashSave(ok ? 'Saved online' : 'Saved on this device · online save failed', ok ? 'ok' : 'err');
  } else {
    flashSave('Saved on this device', 'ok');
  }
}

/* ============================================================================
 * EXPERIMENT PERSISTENCE  +  RENAME OVERRIDES
 * ========================================================================== */
function persistLocal(){
  try{ localStorage.setItem(LS.exps, JSON.stringify(state.experiments)); }catch(e){}
}
function persistNames(){
  try{ localStorage.setItem(LS.names, JSON.stringify(state.names)); }catch(e){}
}
function deleteExperiment(key){
  const g = findGroup(key); if(!g) return;
  const ids = g.items.filter(i=>i.kind==='experiment').map(i=>i.id);
  if(!ids.length) return;
  if(!confirm('Delete this experiment? This cannot be undone.')) return;
  state.experiments = state.experiments.filter(e=>!ids.includes(e.id));
  persistLocal(); render(); ghSave();
}

/* ------------------------------------------------------------- rename UI -- */
let rnKey=null;
function openRename(key){
  const g=findGroup(key); if(!g) return;
  rnKey=key;
  $('#rn-input').value = displayName(key, g.rep.title);
  $('#rename').showModal();
}
function saveRename(){
  if(!rnKey) return;
  const v=$('#rn-input').value.trim();
  const g=findGroup(rnKey);
  if(!v || v===(g&&g.rep.title)){ delete state.names[rnKey]; }
  else state.names[rnKey]=v;
  persistNames(); $('#rename').close(); render();
}
function resetRename(){
  if(rnKey){ delete state.names[rnKey]; persistNames(); }
  $('#rename').close(); render();
}

/* ============================================================================
 * GITHUB SYNC  (Contents API)
 * ========================================================================== */
function ghHeaders(){
  const h = { 'Accept':'application/vnd.github+json' };
  if(state.token) h['Authorization'] = 'Bearer '+state.token;
  return h;
}
// UTF-8 safe base64 round-trip (TextEncoder/TextDecoder) — symmetric and
// correct for em-dashes, curly quotes, emoji etc. Strips ALL whitespace since
// the GitHub Contents API returns base64 with embedded newlines.
function b64decode(s){
  const bin = atob(String(s||'').replace(/\s/g,''));
  const bytes = Uint8Array.from(bin, c=>c.charCodeAt(0));
  return new TextDecoder('utf-8').decode(bytes);
}
function b64encode(s){
  const bytes = new TextEncoder().encode(s);
  let bin=''; bytes.forEach(b=>{ bin+=String.fromCharCode(b); });
  return btoa(bin);
}

// GET experiments.json — returns {experiments, sha, handle} ; 404 -> empty
async function ghLoad(tokenOverride){
  const url = `https://api.github.com/repos/${GH.owner}/${GH.repo}/contents/${GH.path}?ref=${GH.branch}`;
  const headers = { 'Accept':'application/vnd.github+json' };
  const tok = tokenOverride!==undefined ? tokenOverride : state.token;
  if(tok) headers['Authorization'] = 'Bearer '+tok;
  const res = await fetch(url, { headers });
  if(res.status===404) return { experiments:[], sha:null, ok:true };
  if(!res.ok){
    const msg = res.status===401?'Invalid or expired token':(res.status===403?'Access denied (check token scope)':('GitHub error '+res.status));
    throw new Error(msg);
  }
  const j = await res.json();
  let parsed = { experiments:[] };
  try{ const raw = b64decode(j.content); const p = JSON.parse(raw); parsed = Array.isArray(p)?{experiments:p}:p; }catch(e){}
  // who am I (best-effort, only with token)
  let handle=null;
  if(tok){
    try{ const u=await fetch('https://api.github.com/user',{headers}); if(u.ok){ handle=(await u.json()).login; } }catch(e){}
  }
  return { experiments: parsed.experiments||[], sha:j.sha||null, handle, ok:true };
}

// PUT experiments.json (token required) — preserve input on failure.
// Returns true on success, false on failure.
async function ghSave(){
  if(!state.token){ setStatus('ro'); return false; }
  setStatus('saving');
  try{
    // reconcile sha first AND fold in any concurrent remote additions so a
    // last-writer-wins PUT doesn't clobber experiments another client added.
    let sha = state.sha;
    try{
      const cur = await ghLoad();
      sha = cur.sha;
      mergeIntoState(cur.experiments);
    }catch(e){ /* keep existing sha + local state */ }
    const payload = { updated:new Date().toISOString(), experiments: state.experiments };
    const body = {
      message:`Update experiments.json (${state.experiments.length} tests) via Shorts Lab`,
      content: b64encode(JSON.stringify(payload, null, 1)),
      branch: GH.branch,
    };
    if(sha) body.sha = sha;
    const res = await fetch(`https://api.github.com/repos/${GH.owner}/${GH.repo}/contents/${GH.path}`, {
      method:'PUT', headers:ghHeaders(), body:JSON.stringify(body),
    });
    if(!res.ok){
      if(res.status===409) throw new Error('Conflict — someone else saved. Reload and retry.');
      throw new Error('Couldn’t save — '+(res.status===401?'reconnect':('error '+res.status)));
    }
    const j = await res.json();
    state.sha = j.content && j.content.sha;
    state.lastSync = new Date().toISOString();
    state.online = true;
    setStatus('synced');
    return true;
  }catch(err){
    state.online = false;
    setStatus('error', err.message);
    return false;
  }
}

/* ------------------------------------------------------- merge on load --- */
// merge `remote` over the current `local` array, newest _ts wins, by id.
function mergeById(local, remote){
  const byId = new Map();
  (remote||[]).forEach(e=>{ if(e&&e.id) byId.set(e.id, e); });
  (local||[]).forEach(e=>{
    if(!e||!e.id) return;
    const r = byId.get(e.id);
    if(!r || (e._ts||0) >= (r._ts||0)) byId.set(e.id, e);
  });
  return Array.from(byId.values());
}
function mergeExperiments(remote){
  const local = loadJSON(LS.exps, []);
  // NEVER wipe local with empty/unreachable remote
  if(!remote || !remote.length){
    state.experiments = local;
    return;
  }
  state.experiments = mergeById(local, remote);
  persistLocal();
}
// fold concurrent remote additions into the live state (used right before a PUT)
function mergeIntoState(remote){
  if(!remote || !remote.length) return;
  state.experiments = mergeById(state.experiments, remote);
  persistLocal();
}

/* ============================================================================
 * STATUS PILL  +  CONNECT DIALOG  +  READ-ONLY BANNER
 * ========================================================================== */
function setStatus(kind, errMsg){
  const pill = $('#status-pill');
  pill.className = 'status-pill';
  let dot='🔒', word='Read-only';
  if(kind==='synced'){ pill.classList.add('is-synced'); dot='🟢'; word='Synced'+(state.lastSync?' · '+relTime(state.lastSync):''); }
  else if(kind==='saving'){ pill.classList.add('is-saving'); dot='⏳'; word='Saving…'; }
  else if(kind==='error'){ pill.classList.add('is-error'); dot='⚠️'; word='Couldn’t save'; }
  else { pill.classList.add('is-ro'); dot='🔒'; word=state.token?'Read-only':'Read-only'; }
  pill.innerHTML = `<span class="sp-dot">${dot}</span><span class="sp-word">${esc(word)}</span>`;
  pill.title = errMsg || (kind==='synced'?'Saved online':'Connect to save');
  // read-only banner
  const ro = (!state.token || !state.online) && kind!=='saving';
  const showBanner = !state.token; // unmissable when no token at all
  $('#readonly-banner').hidden = !showBanner;
}

let cnValidated=false;
function openConnect(){
  $('#cn-token').value = state.token || '';
  $('#cn-token').classList.remove('ok','bad');
  $('#cn-msg').textContent = state.token ? 'Token present in this browser.' : '';
  $('#cn-msg').className='cn-msg';
  $('#cn-disconnect').hidden = !state.token;
  cnValidated = !!state.token;
  $('#connect').showModal();
}
const validateToken = debounce(async (tok)=>{
  const msg=$('#cn-msg'), input=$('#cn-token');
  if(!tok){ msg.textContent=''; msg.className='cn-msg'; input.classList.remove('ok','bad'); return; }
  msg.textContent='Checking…'; msg.className='cn-msg busy'; input.classList.remove('ok','bad');
  try{
    const r = await ghLoad(tok);
    input.classList.add('ok'); input.classList.remove('bad');
    msg.className='cn-msg ok';
    msg.textContent = `Connected${r.handle?` as @${r.handle}`:''} · shared with editor + AI`;
    cnValidated=true;
  }catch(err){
    input.classList.add('bad'); input.classList.remove('ok');
    msg.className='cn-msg bad'; msg.textContent=err.message; cnValidated=false;
  }
}, 500);

async function connectDone(){
  const tok = $('#cn-token').value.trim();
  if(tok && cnValidated){
    state.token = tok;
    localStorage.setItem(LS.token, tok);
    setStatus('saving');
    try{
      const r = await ghLoad();
      state.sha = r.sha; state.ghHandle = r.handle;
      mergeExperiments(r.experiments);
      state.online = true; state.lastSync = new Date().toISOString();
      setStatus('synced'); render();
    }catch(e){ setStatus('error', e.message); }
  }
  $('#connect').close();
}
function disconnect(){
  state.token=''; localStorage.removeItem(LS.token);
  state.online=false; state.sha=null; state.ghHandle=null;
  setStatus('ro'); $('#connect').close();
}

function flashSave(text, kind){
  const el=$('#at-save-status');
  el.className='save-status'+(kind?' '+kind:'');
  el.textContent=text;
  if(kind!=='busy') setTimeout(()=>{ if(el.textContent===text) el.textContent=''; }, 4000);
}

/* ============================================================================
 * FINDINGS
 * ========================================================================== */
const TRUST_LABEL = {validated:'✅ Validated', directional:'🟡 Directional', craft:'🔵 Craft', method:'⚙️ Method'};
function renderFindings(){
  const wrap = $('#findings');
  if(!state.findings){ wrap.innerHTML='<p class="empty">No findings loaded.</p>'; return; }
  const upd = state.findings.updated;
  $('#findings-stamp').textContent = `Last updated ${upd?esc(upd):'—'} · AI-generated${state.findings.note?'':''}`;
  wrap.innerHTML = (state.findings.findings||[]).map(f=>{
    const t = f.trust||'method';
    const levers = (f.levers||[]).map(l=>`<span class="f-lever">${esc(l)}</span>`).join('');
    return `<div class="finding t-${t}">
      <div class="finding-top">
        <span class="finding-icon">${esc(f.icon||'•')}</span>
        <h3>${esc(f.title)}</h3>
      </div>
      <p class="finding-body">${esc(f.body)}</p>
      <div class="finding-meta">
        <span class="trust t-${t}">${TRUST_LABEL[t]||esc(t)}</span>
        ${f.bucket?`<span class="f-bucket">${esc(f.bucket)}</span>`:''}
        ${levers}
      </div>
      ${f.evidence?`<div class="f-evidence">${esc(f.evidence)}</div>`:''}
    </div>`;
  }).join('');
}

/* ============================================================================
 * TABS
 * ========================================================================== */
function switchTab(tab){
  state.tab = tab;
  $$('.tab').forEach(t=>{
    const on=t.dataset.tab===tab; t.classList.toggle('is-active',on); t.setAttribute('aria-selected',on);
  });
  $('#view-library').hidden = tab!=='library';
  $('#view-library').classList.toggle('is-active', tab==='library');
  $('#view-findings').hidden = tab!=='findings';
  $('#view-findings').classList.toggle('is-active', tab==='findings');
  if(tab==='findings') renderFindings();
  syncURL();
}

/* ============================================================================
 * EVENT WIRING (delegated)
 * ========================================================================== */
function wireEvents(){
  // toolbar
  $('#search').addEventListener('input', debounce(e=>{ state.q=e.target.value; render(); }, 160));
  $('#sort').addEventListener('change', e=>{ state.sort=e.target.value; render(); });
  $('#dir').addEventListener('click', ()=>{ state.dir = state.dir==='asc'?'desc':'asc'; render(); });
  $$('.vt-btn').forEach(b=>b.addEventListener('click', ()=>{ state.view=b.dataset.view; render(); }));
  $('#chips').addEventListener('click', e=>{
    const c=e.target.closest('[data-filter]'); if(!c) return;
    state.filter=c.dataset.filter; render();
  });
  // tabs
  $$('.tab').forEach(t=>t.addEventListener('click', ()=>switchTab(t.dataset.tab)));

  // grid (delegated): card click, add, menu, rename, edit, delete
  $('#grid').addEventListener('click', onLibraryClick);
  $('#table-wrap').addEventListener('click', onLibraryClick);

  // top chrome
  $('#new-blank').addEventListener('click', ()=>openAddTest(null));
  $('#status-pill').addEventListener('click', openConnect);
  $('#banner-connect').addEventListener('click', openConnect);

  // add-test drawer
  $('#at-close').addEventListener('click', ()=>$('#addtest').close());
  $('#at-cancel').addEventListener('click', ()=>$('#addtest').close());
  $('#at-save').addEventListener('click', saveVersion);
  // form-level delegation attached ONCE (the form element persists across rebuilds)
  $('#at-form').addEventListener('input', onFormChange);
  $('#at-form').addEventListener('change', onFormChange);

  // connect dialog
  $('#cn-close').addEventListener('click', ()=>$('#connect').close());
  $('#cn-done').addEventListener('click', connectDone);
  $('#cn-disconnect').addEventListener('click', disconnect);
  $('#cn-token').addEventListener('input', e=>{ cnValidated=false; validateToken(e.target.value.trim()); });

  // rename dialog
  $('#rn-close').addEventListener('click', ()=>$('#rename').close());
  $('#rn-save').addEventListener('click', saveRename);
  $('#rn-reset').addEventListener('click', resetRename);

  // dialogs: Esc + backdrop close.
  // Only close when a click BOTH starts and ends on the dialog backdrop (the
  // <dialog> element itself, outside .drawer-inner/.modal-inner). This prevents
  // an accidental close when a drag/select starts on an input and the mouseup
  // lands on the backdrop mid-edit.
  ['detail','addtest','connect','rename'].forEach(id=>{
    const d=$('#'+id);
    let downOnBackdrop=false;
    d.addEventListener('pointerdown', e=>{
      downOnBackdrop = (e.target===d) && !e.target.closest('.drawer-inner, .modal-inner');
    });
    d.addEventListener('click', e=>{
      const upOnBackdrop = (e.target===d) && !e.target.closest('.drawer-inner, .modal-inner');
      if(downOnBackdrop && upOnBackdrop) d.close();
      downOnBackdrop=false;
    });
    d.addEventListener('close', ()=>{ if(id==='detail'){ $('#detail').dataset.key=''; syncURL(); } });
  });

  // close any open card menu on outside click
  document.addEventListener('click', e=>{
    if(!e.target.closest('.menu-wrap')) $$('.menu.open').forEach(m=>m.classList.remove('open'));
  });

  // browser back/forward
  window.addEventListener('popstate', ()=>{
    const slug = readURL();
    applyStateToUI();
    switchTab(state.tab);   // always sync the visible panel for both directions
    render();
    if(slug){ const g=findGroupBySlug(slug); if(g) openDetail(g.key); }
    else closeDetail();
  });
}

function onLibraryClick(e){
  // stop-propagation zones (yt link, action cluster handled individually)
  const add = e.target.closest('[data-add]');
  if(add){ e.stopPropagation(); openAddTest(add.dataset.add); return; }
  const menuBtn = e.target.closest('[data-menu]');
  if(menuBtn){ e.stopPropagation(); const m=menuBtn.parentElement.querySelector('.menu');
    $$('.menu.open').forEach(x=>{ if(x!==m) x.classList.remove('open'); }); m.classList.toggle('open'); return; }
  const ren = e.target.closest('[data-rename]'); if(ren){ e.stopPropagation(); openRename(ren.dataset.rename); return; }
  const ed = e.target.closest('[data-edit]'); if(ed){ e.stopPropagation(); openEditExperiment(ed.dataset.edit); return; }
  const del = e.target.closest('[data-del]'); if(del){ e.stopPropagation(); deleteExperiment(del.dataset.del); return; }
  if(e.target.closest('[data-stop]')) { if(e.target.closest('a')) return; e.stopPropagation(); return; }
  // whole-card / row click → detail
  const host = e.target.closest('[data-key]');
  if(host) openDetail(host.dataset.key);
}

function applyStateToUI(){
  $('#search').value=state.q; $('#sort').value=state.sort;
  $('#dir').textContent=state.dir==='asc'?'▲':'▼';
}

/* ============================================================================
 * BOOT
 * ========================================================================== */
async function boot(){
  wireEvents();

  // restore UI state + name overrides
  state.names = loadJSON(LS.names, {});
  // URL params win (shareable links); otherwise fall back to the localStorage
  // mirror of {sort,dir,filter,view}.
  const hadURLState = /[?&](sort|dir|filter|q|view|tab)=/.test(location.search);
  const deepShort = readURL();
  if(!hadURLState){
    const ui = loadJSON(LS.ui, null);
    if(ui){
      if(ui.sort)   state.sort   = ui.sort;
      if(ui.dir)    state.dir    = ui.dir;
      if(ui.filter) state.filter = ui.filter;
      if(ui.view)   state.view   = ui.view;
    }
  }

  // fetch data + findings
  let data=null;
  try{ data = await (await fetch('data.json',{cache:'no-cache'})).json(); }
  catch(e){ data = {videos:[],predictions:[],schema:null}; }
  state.videos = data.videos||[];
  state.predictions = data.predictions||[];
  state.schema = data.schema || null;
  state.generated = data.generated || null;

  try{ state.findings = await (await fetch('findings.json',{cache:'no-cache'})).json(); }
  catch(e){ state.findings = null; }

  // experiments: GitHub first, then localStorage, then static experiments.json (seed-only)
  let remoteExps = null, gotRemote = false;
  try{
    const r = await ghLoad();
    remoteExps = r.experiments; state.sha=r.sha; state.ghHandle=r.handle;
    gotRemote = true;
    if(state.token){ state.online=true; state.lastSync=new Date().toISOString(); }
  }catch(e){ remoteExps=null; gotRemote=false; }

  if(gotRemote){
    // authoritative remote (GitHub) — merge by id, newest wins
    mergeExperiments(remoteExps);
  } else {
    // offline / no token: localStorage is the source of truth.
    // The committed static experiments.json is SEED-ONLY (it can be stale and
    // does not represent local deletions) — use it only when local is empty.
    const local = loadJSON(LS.exps, []);
    if(local.length){
      state.experiments = local;
    } else {
      let seed = null;
      try{ const s = await (await fetch('experiments.json',{cache:'no-cache'})).json();
        seed = Array.isArray(s)?s:(s.experiments||null); }
      catch(e){ seed = null; }
      mergeExperiments(seed);
    }
  }

  // status pill
  setStatus(state.token ? (state.online?'synced':'ro') : 'ro');

  // tab + render
  if(state.tab==='findings') switchTab('findings'); else switchTab('library');
  render();

  // deep link to a short
  if(deepShort){ const g=findGroupBySlug(deepShort); if(g) openDetail(g.key); }
}

document.addEventListener('DOMContentLoaded', boot);
